### ISSUE TITLE
How to stop container creating logs/dirs as root?

### ISSUE THREAD

**Issue by timdonovanuk** [balabit/syslog-ng-docker#68]
I use a destination that stores the logs on a mounted docker volume, e.g.:

docker stack:
```
  syslogng:
    image: balabit/syslog-ng
    ports:
      - 514:514/udp
    volumes:
      - /opt/syslog-ng/log:/var/log/syslog-ng    
      - /opt/syslog-ng:/etc/syslog-ng 
```

syslog-ng.conf:
```
destination logfiles {
    file("/var/log/syslog-ng/$PROGRAM/$PROGRAM.log");
};
```

How do I stop syslog-ng-docker creating every log file and directory as root? Thanks!
